export const swarmCoordinatorAbi = [
  {
    type: "constructor",
    inputs: [
      { name: "_usdc", type: "address" },
      { name: "_treasury", type: "address" },
    ],
    stateMutability: "nonpayable",
  },
  // === Write Functions ===
  {
    type: "function",
    name: "createTask",
    inputs: [
      { name: "reward", type: "uint256" },
      { name: "bondRequired", type: "uint256" },
      { name: "descriptionHash", type: "string" },
      { name: "deadline", type: "uint256" },
      { name: "parentTaskId", type: "uint256" },
    ],
    outputs: [{ name: "taskId", type: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "claimTask",
    inputs: [{ name: "taskId", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "submitWork",
    inputs: [
      { name: "taskId", type: "uint256" },
      { name: "proofHash", type: "string" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "approveWork",
    inputs: [{ name: "taskId", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "cancelTask",
    inputs: [{ name: "taskId", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "openDispute",
    inputs: [{ name: "taskId", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "castVote",
    inputs: [
      { name: "disputeId", type: "uint256" },
      { name: "inFavorOfAssignee", type: "bool" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "registerJuror",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  // === View Functions ===
  {
    type: "function",
    name: "getTask",
    inputs: [{ name: "taskId", type: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "id", type: "uint256" },
          { name: "creator", type: "address" },
          { name: "assignee", type: "address" },
          { name: "reward", type: "uint256" },
          { name: "bondAmount", type: "uint256" },
          { name: "parentTaskId", type: "uint256" },
          { name: "status", type: "uint8" },
          { name: "descriptionHash", type: "string" },
          { name: "proofHash", type: "string" },
          { name: "deadline", type: "uint256" },
          { name: "createdAt", type: "uint256" },
          { name: "childCount", type: "uint256" },
          { name: "childCompleted", type: "uint256" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getDispute",
    inputs: [{ name: "disputeId", type: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "taskId", type: "uint256" },
          { name: "jurors", type: "address[3]" },
          { name: "votes", type: "bool[3]" },
          { name: "voteCount", type: "uint8" },
          { name: "resolved", type: "bool" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getJurorPoolSize",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "taskCount",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "disputeCount",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "registeredJurors",
    inputs: [{ name: "", type: "address" }],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "usdc",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "treasury",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "PLATFORM_FEE_BPS",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "MIN_REWARD",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "hasVoted",
    inputs: [
      { name: "", type: "uint256" },
      { name: "", type: "address" },
    ],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  // === Events ===
  {
    type: "event",
    name: "TaskCreated",
    inputs: [
      { name: "taskId", type: "uint256", indexed: true },
      { name: "creator", type: "address", indexed: true },
      { name: "reward", type: "uint256", indexed: false },
      { name: "parentTaskId", type: "uint256", indexed: false },
      { name: "descriptionHash", type: "string", indexed: false },
    ],
  },
  {
    type: "event",
    name: "TaskClaimed",
    inputs: [
      { name: "taskId", type: "uint256", indexed: true },
      { name: "assignee", type: "address", indexed: true },
      { name: "bondAmount", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "WorkSubmitted",
    inputs: [
      { name: "taskId", type: "uint256", indexed: true },
      { name: "proofHash", type: "string", indexed: false },
    ],
  },
  {
    type: "event",
    name: "WorkApproved",
    inputs: [
      { name: "taskId", type: "uint256", indexed: true },
      { name: "payout", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "DisputeOpened",
    inputs: [
      { name: "taskId", type: "uint256", indexed: true },
      { name: "disputeId", type: "uint256", indexed: true },
    ],
  },
  {
    type: "event",
    name: "DisputeVoteCast",
    inputs: [
      { name: "disputeId", type: "uint256", indexed: true },
      { name: "juror", type: "address", indexed: true },
      { name: "inFavorOfAssignee", type: "bool", indexed: false },
    ],
  },
  {
    type: "event",
    name: "DisputeResolved",
    inputs: [
      { name: "disputeId", type: "uint256", indexed: true },
      { name: "taskId", type: "uint256", indexed: true },
      { name: "inFavorOfAssignee", type: "bool", indexed: false },
    ],
  },
  {
    type: "event",
    name: "TaskCancelled",
    inputs: [
      { name: "taskId", type: "uint256", indexed: true },
      { name: "refund", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "JurorRegistered",
    inputs: [{ name: "juror", type: "address", indexed: true }],
  },
  // === Errors ===
  { type: "error", name: "InvalidReward", inputs: [] },
  { type: "error", name: "InvalidDeadline", inputs: [] },
  { type: "error", name: "TaskNotOpen", inputs: [] },
  { type: "error", name: "TaskNotSubmitted", inputs: [] },
  { type: "error", name: "TaskNotClaimed", inputs: [] },
  { type: "error", name: "TaskNotDisputed", inputs: [] },
  { type: "error", name: "NotTaskCreator", inputs: [] },
  { type: "error", name: "NotTaskAssignee", inputs: [] },
  { type: "error", name: "CannotClaimOwnTask", inputs: [] },
  { type: "error", name: "DeadlinePassed", inputs: [] },
  { type: "error", name: "AlreadyRegisteredJuror", inputs: [] },
  { type: "error", name: "NotRegisteredJuror", inputs: [] },
  { type: "error", name: "InsufficientJurors", inputs: [] },
  { type: "error", name: "JurorIsParty", inputs: [] },
  { type: "error", name: "AlreadyVoted", inputs: [] },
  { type: "error", name: "DisputeAlreadyResolved", inputs: [] },
  { type: "error", name: "ChildTasksIncomplete", inputs: [] },
  { type: "error", name: "ParentRewardExceeded", inputs: [] },
] as const;

export const erc20Abi = [
  {
    type: "function",
    name: "approve",
    inputs: [
      { name: "spender", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "allowance",
    inputs: [
      { name: "owner", type: "address" },
      { name: "spender", type: "address" },
    ],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "balanceOf",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "decimals",
    inputs: [],
    outputs: [{ name: "", type: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "symbol",
    inputs: [],
    outputs: [{ name: "", type: "string" }],
    stateMutability: "view",
  },
] as const;
